theme: jekyll-theme-minimal
title: Ojas Kulkarn

# Personal info
name: Your Name
title: Your job title
email: Your email (optional)
# email_title: Email (Email title override)
phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false
